[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
solc-optimizer = true
solc-optimizer-runs = 200
viaIR = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/"
    ]

[etherscan]
48899 = { key = "F757C4CD44C537876C85C7831B7BBE6952", url = "https://explorer.zircuit.com/api/contractVerifyHardhat" }
18 = { key = "verifyContract", url = "http://explorer-testnet.thundercore.co" }
